networks: 
  my-networks:
    driver: bridge

volumes:
  performance_app:
  vectorstore_data:
  documents:

services:
  performance-app:
    image: python:3.12
    ports:
      - "7860:7860"
    networks:
      - my-networks
    # ADD DNS SETTINGS TO FIX NETWORK CONNECTIVITY
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - .:/app
      - performance_app:/usr/local/lib/python3.12/site-packages
      - documents:/app/documents
    working_dir: /app
    deploy:
      #resources:
        #reservations:
          #devices:
            #- driver: nvidia
              #count: 1
              #capabilities: ["gpu"]
    command: >
      bash -c "pip install --upgrade pip && pip install -r /app/requirements.txt && pip install hf_xet && python -m spacy download en_core_web_md && python -u /app/main.py"
    depends_on:
      - performance-vectorstore
      
  performance-vectorstore:
    image: chromadb/chroma
    networks:
      - my-networks
    volumes:
      - vectorstore_data:/chroma/chroma
    ports:
      - "8000:8000"